### ISSUE TITLE
关于此项目

### ISSUE THREAD

**Issue by JasonWu008** [shuiRong/Eva#1]
请问这个项目能够搭建个人博客吗

**Comment by shuiRong** [comment]
遵循[快速开始](https://github.com/shuiRong/Eva/blob/master/quickstart_zh.md)可以搭建起来，你可以在本地搭建一遍后，再在服务器上搭建。

另外，如果你是在找一个博客项目的话，我更建议你选择：Hexo + Github Pages 来搭建静态博客。我现在的[博客](https://linshuirong.cn) 就是这样。这种方式如何来网上教程很多，你Google上面的关键词即可。

**Comment by JasonWu008** [comment]
感谢回复
